apiVersion : apps/v1
kind: Deployment
metadata:
  name: adityamehtagitpipelinesjavascriptdocker 
  labels:
     app: adityamehtagitpipelinesjavascriptdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adityamehtagitpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: adityamehtagitpipelinesjavascriptdocker 
    spec:
      containers:
        - name: adityamehtagitpipelinesjavascriptdocker 
          image: aksacrcentralus.azurecr.io/adityamehtagitpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
